name: pheast
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bioconductor-impute  # for covariates
  - bioconductor-qvalue  # for tensorqtl
  - bioconductor-variantannotation  # for covariates
  - dask<2024.2  # for tensorqtl (pandas-plink)
  - gcta  # for heritability
  - pandas
  - pandas-plink  # for tensorqtl
  - pip
  - plink
  - plink2=2
  - r-glmnet  # for FUSION
  - r-optparse
  - rpy2  # for tensorqtl
  - snakemake
  - snakemake-executor-plugin-slurm # change as needed for your cluster
  - pip:
    - tensorqtl
    - torch==2.3.1 # for tensorqtl
